# Generated by Django 4.2.6 on 2023-11-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='tot_votes',
            field=models.IntegerField(default=0),
        ),
    ]
