# Generated by Django 4.2.6 on 2023-11-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_tot_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='tot_votes',
        ),
        migrations.AddField(
            model_name='question',
            name='tot_votes',
            field=models.IntegerField(default=0),
        ),
    ]
