# Generated by Django 4.2.6 on 2023-10-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeParam1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_nom', models.CharField(max_length=200)),
                ('param_date', models.DateTimeField(verbose_name='publication')),
            ],
        ),
    ]
