# Generated by Django 4.2.6 on 2023-11-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plante_texte', models.CharField(max_length=200)),
                ('plante_ec_min', models.DecimalField(decimal_places=2, max_digits=2)),
                ('plante_ec_max', models.DecimalField(decimal_places=2, max_digits=2)),
                ('plante_ph_min', models.DecimalField(decimal_places=2, max_digits=2)),
                ('plante_ph_max', models.DecimalField(decimal_places=2, max_digits=2)),
                ('plante_prod', models.CharField(max_length=200)),
            ],
        ),
    ]
